# Launch ofono2mm in place of ModemManager

[Unit]
Wants=ofono.service NetworkManager.service
After=ofono.service NetworkManager.service
StartLimitBurst=20

[Service]
ExecStart=
ExecStart=/usr/sbin/ofono2mm
Type=simple
RestartSec=1
TimeoutStartSec=5
Restart=always
StandardOutput=journal
StandardError=journal
NoNewPrivileges=false
CapabilityBoundingSet=CAP_SYS_ADMIN CAP_NET_ADMIN CAP_SETUID
